### ISSUE TITLE
macOS High Sierra support

### ISSUE THREAD

**Issue by MaorS** [tuan188/MGTextPlus#1]
Since I upgraded to macOS High Sierra 10.13
I can not use this plugin at all.
Can't find "TextPlus" over "System Preferences"

**Comment by tuan188** [comment]
Please check System Preferences > Extensions > Xcode Source Editor
I'm using macOS High Sierra.
<img width="780" alt="screen shot 2017-09-28 at 6 35 36 pm" src="https://user-images.githubusercontent.com/6461902/30964573-19b4dee4-a47c-11e7-8b87-eb38502f2beb.png">
