### ISSUE TITLE
Change `class` to `AnyObject` for protocols

### ISSUE THREAD

**Issue by jrdtrifork** [tuan188/MGTextPlus#14]
I get this warning when i generate a protocol:
`Using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead`

Could you change `class` to `AnyObject` 🙂

`protocol MyViewControllerDelegate: class {}`
to
`protocol MyViewControllerDelegate: AnyObject {}`

Thanks

**Comment by tuan188** [comment]
@jrdtrifork Please update to version 1.5.3.

**Comment by jrdtrifork** [comment]
Thanks 🙂
