### ISSUE TITLE
Split Line by Comma shouldn't split up placeholder values

### ISSUE THREAD

**Issue by ZevEisenberg** [tuan188/MGTextPlus#15]
Splitting line by commas should ignore placeholder values, which Xcode expresses using various combinations of `<`, `>`, and `#`.

Given this line:

```swift
self.init(embed: <#T##(Value, inout Root) -> Void#>, extract: <#T##(Root) -> Value?#>)
```

Which renders like this:

<img width="763" alt="image" src="https://user-images.githubusercontent.com/464574/176276869-8f6c17ce-2279-4f38-9b60-fbf9e17aba26.png">

## Expected

Calling "Split Line by Comma" should result in this:

```swift
self.init(embed: <#T##(Value, inout Root) -> Void#>,
          extract: <#T##(Root) -> Value?#>)
```

Which renders like this:

<img width="378" alt="image" src="https://user-images.githubusercontent.com/464574/176277013-649588d6-fa66-4f26-8a00-6d9915be8f1e.png">

## Observed

But instead it does this:

```swift
self.init(embed: <#T##(Value,
                       inout Root) -> Void#>,
                       extract: <#T##(Root) -> Value?#>)
```

Which renders like this:

<img width="406" alt="image" src="https://user-images.githubusercontent.com/464574/176277192-22f61f30-8d03-4e63-a440-72b12127589f.png">

**Comment by tuan188** [comment]
@ZevEisenberg 
This bug has been fixed in version 1.5.4

![split](https://user-images.githubusercontent.com/6461902/178861774-7918c90e-7dd3-482d-82be-50828dc3cfd7.gif)
