### ISSUE TITLE
Xcode 12 & catalina

### ISSUE THREAD

**Issue by fatlazycat** [tuan188/MGTextPlus#8]
Hi, installed the app but see nothing to enable it

System Preferences -> Extensions -> Xcode Source Editor

Have no Xcode Source Editor in extensions.

Thanks

**Comment by tuan188** [comment]
Make sure you run the app at least once.
I found someone with similar problems, please follow this link to see if it can help:
https://github.com/nicklockwood/SwiftFormat/issues/494
https://support.swiftify.com/hc/en-us/articles/360030396531-Swiftify-s-Xcode-Extension-is-missing

**Comment by fatlazycat** [comment]
Thanks, renaming Xcode to something else and then back to Xcode fixed it.

Getting depressing the state of Apple these days.

**Comment by NikKovIos** [comment]
Can't believe, but it helped. Steve J, so miss you...
