### ISSUE TITLE
Xcode 12.2 support

### ISSUE THREAD

**Issue by alex93133** [tuan188/MGTextPlus#9]
I have some issues with Xcode 12.2. I have enabled the extension in System Preferences like always, but it doesn't show up in the Editor menu.

**Comment by tuan188** [comment]
I also got this issue, reinstalling Xcode or macOS didn't help. It happens with other extensions as well.
Seems like there is a problem with macOS Big Sur and Xcode 12.2.

**Comment by tuan188** [comment]
https://developer.apple.com/forums/thread/666434
> Source Editor extensions now need to link / embed & sign the XcodeKit framework

**Comment by alex93133** [comment]
I'm waiting for an update or another new info because the extension is so useful for me)

**Comment by tuan188** [comment]
This issue has been fixed in version 1.5.1
https://github.com/tuan188/MGTextPlus/releases/tag/1.5.1

Please wait 1-2 days until it becomes available on the App Store.

**Comment by alex93133** [comment]
Awesome!
